# Generated by Django 2.0.7 on 2018-11-15 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='rbac_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登录用户'),
        ),
        migrations.AddField(
            model_name='studyrecord',
            name='course_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.CourseRecord', verbose_name='第几天课程'),
        ),
        migrations.AddField(
            model_name='studyrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Student', verbose_name='上课学生'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_list',
            field=models.ManyToManyField(blank=True, to='crm.ClassList', verbose_name='已报班级'),
        ),
        migrations.AddField(
            model_name='student',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='客户信息'),
        ),
        migrations.AddField(
            model_name='mycustomers',
            name='consultant',
            field=models.ForeignKey(limit_choices_to={'depart': 1001}, on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='咨询顾问'),
        ),
        migrations.AddField(
            model_name='mycustomers',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='customer',
            name='consultant',
            field=models.ForeignKey(limit_choices_to={'depart': 1001}, on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='咨询顾问'),
        ),
        migrations.AddField(
            model_name='customer',
            name='purpose_course',
            field=models.ManyToManyField(blank=True, to='crm.Course', verbose_name='咨询课程'),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_from',
            field=models.ForeignKey(blank=True, help_text='若此客户是转介绍自内部学员,请在此处选择内部学员姓', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='转介绍自学员'),
        ),
        migrations.AddField(
            model_name='courserecord',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ClassList', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='courserecord',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'depart__in': [1002, 1003]}, on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='上课老师'),
        ),
        migrations.AddField(
            model_name='consultrecord',
            name='consultant',
            field=models.ForeignKey(limit_choices_to={'depart': 1001}, on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='跟踪人'),
        ),
        migrations.AddField(
            model_name='consultrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='咨询客户'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Course', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.School', verbose_name='校区'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'depart__in': [1002, 1005]}, related_name='classlist_teacher', to='crm.UserInfo', verbose_name='任课老师'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'depart': 1001}, on_delete=django.db.models.deletion.CASCADE, related_name='classlist_tutor', to='crm.UserInfo', verbose_name='班主任'),
        ),
    ]
